# Generated by Django 2.2.2 on 2019-06-26 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0005_auto_20190625_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='solvers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.CharField(max_length=200),
        ),
    ]
