# Generated by Django 2.2.2 on 2019-06-26 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_auto_20190626_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solvers',
            field=models.ManyToManyField(related_name='solver', to=settings.AUTH_USER_MODEL),
        ),
    ]
