# Generated by Django 2.2.2 on 2019-06-26 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20190626_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solvers',
            field=models.ManyToManyField(related_name='solves', to=settings.AUTH_USER_MODEL),
        ),
    ]
