# Generated by Django 2.2.2 on 2019-06-26 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20190626_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 6, 26)),
        ),
    ]
