# Generated by Django 2.2.2 on 2019-06-26 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_problem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
