# Generated by Django 2.2.2 on 2019-06-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20190626_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='solvedBy',
            new_name='no_of_solvers',
        ),
        migrations.AlterField(
            model_name='problem',
            name='tag',
            field=models.ManyToManyField(related_name='problems', to='problems.Tag'),
        ),
    ]
