# Generated by Django 2.2.2 on 2019-06-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20190627_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='no_of_solvers',
            field=models.IntegerField(null=True),
        ),
    ]
