# Generated by Django 2.2.2 on 2019-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_auto_20190627_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
