# Generated by Django 2.2.2 on 2019-06-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_auto_20190628_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='tag',
            new_name='tags',
        ),
    ]
