# Generated by Django 2.2.2 on 2019-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_auto_20190629_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
