# Generated by Django 2.2.2 on 2019-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_remove_problem_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
