# Generated by Django 2.2.2 on 2019-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20190701_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='solution_submitted',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
