# Generated by Django 2.2.2 on 2019-06-29 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
